---
- name: Update Rocky Linux servers using dnf
  hosts: all
  become: no

  tasks:
    - name: Update all packages to the latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
